### ISSUE TITLE
Theming 

### ISSUE THREAD

**Issue by SanderTuit** [darvds/RibbonMenu#2]
I'm using Holo Dark in my application, which makes the text illegible. Adding 'android:theme="@android:style/Theme.Holo.Light"' to the RibbonMenuView does not help and there is no textColor attribute for this View. 

Is there any solution for this? Thanks!

**Comment by darvds** [comment]
I've not implemented any theming yet, but by default it should work fine with Holo Dark. The text should automatically be white on a dark background.

For now you can simply change the textColor of the TextView in rbm_item.xml.

**Comment by SanderTuit** [comment]
Yes, thanks, that'll do it. I'm using Holo Light, not Dark, sorry about that. It's even a derivative theme, not Holo Light itself.
