### ISSUE TITLE
CacheColorHint issue

### ISSUE THREAD

**Issue by bramt** [darvds/RibbonMenu#5]
Hi
Library looks very nice. I had a problem when using it on a pre-honeycomb device: awful black bleeding through the list whenever it is touched. This also happens on honeycomb+ devices if minSDKversion is set below honeycomb.
To get around it, all that's needed is to set the cacheColorHint to the same colour as the background on the ListView:
android:cacheColorHint="#303030" 
android:background="#303030"
As described a long time ago, here: http://www.curious-creature.org/2008/12/22/why-is-my-list-black-an-android-optimization/
Annoying problem. Simple fix.
There is another small issue with setting the background in your code:

```
public void setBackgroundColor(int color){
        rbmListView.setBackgroundResource(color);

    }
```

That's kinda mis-named I think. You are overriding the method to set a colour in order to set a resource instead.

**Comment by darvds** [comment]
Thanks. I've added the cacheColorHint and renamed that method to make more sense.
